// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "index": {
      name: "index",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "style": {
      name: "style",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "alert": {
      name: "alert",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/ui/alert.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/alert.tsx")),
      source: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      chunks: []
    },
    "compose-refs": {
      name: "compose-refs",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/lib/compose-refs.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/compose-refs.ts")),
      source: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/hooks/use-mobile.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.ts")),
      source: "",
      chunks: []
    },
    "alert-action-demo": {
      name: "alert-action-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["alert"],
      files: [{
        path: "src/registry/default/examples/alert-action-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/alert-action-demo.tsx")),
      source: "",
      chunks: []
    },
    "client-only": {
      name: "client-only",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/components/client-only.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/client-only.tsx")),
      source: "",
      chunks: []
    },
    "direction-provider": {
      name: "direction-provider",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/components/direction-provider.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/direction-provider.tsx")),
      source: "",
      chunks: []
    },
    "portal": {
      name: "portal",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/components/portal.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/portal.tsx")),
      source: "",
      chunks: []
    },
    "presence": {
      name: "presence",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/components/presence.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/presence.tsx")),
      source: "",
      chunks: []
    },
    "visually-hidden": {
      name: "visually-hidden",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/components/visually-hidden.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/visually-hidden.tsx")),
      source: "",
      chunks: []
    },
    "visually-hidden-input": {
      name: "visually-hidden-input",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "src/registry/default/components/visually-hidden-input.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/visually-hidden-input.tsx")),
      source: "",
      chunks: []
    },
  },
}
